# Generated by Django 6.0.5 on 2026-05-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Haircut', 'Haircut'), ('Beard Trim', 'Beard Trim'), ('Haircut + Beard', 'Haircut + Beard'), ('Kids Cut', 'Kids Cut'), ('Fade', 'Fade')], max_length=100)),
                ('barber_name', models.CharField(choices=[('Gina', 'Gina'), ('Tere', 'Tere'), ('Third', 'Third')], max_length=100)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('zelle', 'Zelle')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'unique_together': {('barber_name', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
