# Generated by Django 6.0.5 on 2026-05-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('Haircut', 'Haircut'), ('Beard Trim', 'Beard Trim'), ('Haircut + Beard', 'Haircut + Beard'), ('Kids Cut', 'Kids Cut'), ('Fade', 'Fade')], max_length=100)),
                ('barber', models.CharField(choices=[('Gina', 'Gina'), ('Tere', 'Tere'), ('Third', 'Third')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
